apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname
spec:
  provider: azure
  secretObjects:
  - secretName: mysql-secrets
    type: Opaque
    data:
    - objectName: root-password
      key: root-password
    - objectName: username
      key: username
    - objectName: user-password
      key: user-password
  parameters:
    usePodIdentity: "false"  
    useVMManagedIdentity: "true"  
    userAssignedIdentityID: "$new_test"
    keyvaultName: "kvdinesh007-PROD"
    objects:  |
      array:
        - |
          objectName: root-password
          objectType: secret
        - |
          objectName: username
          objectType: secret
        - |
          objectName: user-password
          objectType: secret
    tenantId: "ed342ee6-bc79-4cea-b4d6-c4ec15b97dac"
